# Generated by Django 5.2 on 2025-04-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lager_app', '0002_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='education/')),
            ],
        ),
    ]
